export interface SeoRouteConfig {
  path: string;
  title: string;
  description: string;
  canonical: string;
  breadcrumbs: { label: string; path: string }[];
  schemaType: 'WebSite' | 'WebApplication' | 'WebPage';
  includeInSitemap: boolean;
}

export const BASE_URL = 'https://resizefiles.pages.dev';

export const SEO_ROUTES: Record<string, SeoRouteConfig> = {
  '/': {
    path: '/',
    title: 'ResizeFiles – Free Image Resizer, Compressor & PDF Tools',
    description: 'Free online image and PDF tools for resizing, compressing and converting files. Process supported files directly in your browser with a privacy-focused workflow.',
    canonical: `${BASE_URL}/`,
    breadcrumbs: [{ label: 'Home', path: '/' }],
    schemaType: 'WebSite',
    includeInSitemap: true,
  },
  '/image-resizer': {
    path: '/image-resizer',
    title: 'Image Resizer Online – Resize JPG, PNG & WebP',
    description: 'Quickly resize image dimensions in pixels or percentages. Change width and height while maintaining aspect ratios or setting custom dimensions directly in your browser.',
    canonical: `${BASE_URL}/image-resizer`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Image Resizer', path: '/image-resizer' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/compress-image': {
    path: '/compress-image',
    title: 'Compress Image Online – Reduce JPG, PNG & WebP Size',
    description: 'Reduce photo and image file sizes in KB or MB without losing visual quality. Optimized for fast web uploads, email attachments, and application forms.',
    canonical: `${BASE_URL}/compress-image`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Compress Image', path: '/compress-image' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/photo-resizer': {
    path: '/photo-resizer',
    title: 'Photo Resizer Online – Resize Images Easily',
    description: 'Resize your photographs to exact dimensions and KB limits required by government portals, job applications, and university entrance forms.',
    canonical: `${BASE_URL}/photo-resizer`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Photo Resizer', path: '/photo-resizer' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/signature-resizer': {
    path: '/signature-resizer',
    title: 'Signature Resizer – Resize Signature Image Online',
    description: 'Crop, resize, and compress your scanned signature to strict upload requirements (under 20KB) for UPSC, SSC, Banking, and NEET forms.',
    canonical: `${BASE_URL}/signature-resizer`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Signature Resizer', path: '/signature-resizer' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/passport-photo-resizer': {
    path: '/passport-photo-resizer',
    title: 'Passport Photo Resizer – Resize Photo Online',
    description: 'Easily resize passport photographs to standard dimensions and file sizes (50KB or 100KB) with automatic aspect ratio correction.',
    canonical: `${BASE_URL}/passport-photo-resizer`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Passport Photo Resizer', path: '/passport-photo-resizer' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/jpg-to-png': {
    path: '/jpg-to-png',
    title: 'JPG to PNG Converter – Convert JPG Images to PNG',
    description: 'Convert JPG images to transparent PNG format instantly in your browser with zero quality loss and complete privacy.',
    canonical: `${BASE_URL}/jpg-to-png`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Image Converters', path: '/jpg-to-png' }, { label: 'JPG to PNG', path: '/jpg-to-png' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/background-remover': {
    path: '/background-remover',
    title: 'Background Remover – Remove Image Background Online',
    description: 'Remove backgrounds from images directly in your browser. Create transparent PNG images with a fast, privacy-focused background remover.',
    canonical: `${BASE_URL}/background-remover`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Background Remover', path: '/background-remover' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/png-to-jpg': {
    path: '/png-to-jpg',
    title: 'PNG to JPG Converter – Convert PNG Images to JPG',
    description: 'Convert PNG images to standard JPEG/JPG format with adjustable quality settings and lightweight file sizes.',
    canonical: `${BASE_URL}/png-to-jpg`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Image Converters', path: '/png-to-jpg' }, { label: 'PNG to JPG', path: '/png-to-jpg' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/jpg-to-webp': {
    path: '/jpg-to-webp',
    title: 'JPG to WebP Converter – Convert JPG to WebP',
    description: 'Convert JPG photos to modern WebP format for faster web loading and superior compression ratios.',
    canonical: `${BASE_URL}/jpg-to-webp`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Image Converters', path: '/jpg-to-webp' }, { label: 'JPG to WebP', path: '/jpg-to-webp' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/png-to-webp': {
    path: '/png-to-webp',
    title: 'PNG to WebP Converter – Convert PNG to WebP',
    description: 'Convert transparent PNG images to next-gen WebP format with high visual fidelity and reduced file size.',
    canonical: `${BASE_URL}/png-to-webp`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Image Converters', path: '/png-to-webp' }, { label: 'PNG to WebP', path: '/png-to-webp' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/webp-to-jpg': {
    path: '/webp-to-jpg',
    title: 'WebP to JPG Converter – Convert WebP Images to JPG',
    description: 'Convert WebP images back to universally compatible JPG/JPEG format for easy sharing and printing.',
    canonical: `${BASE_URL}/webp-to-jpg`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Image Converters', path: '/webp-to-jpg' }, { label: 'WebP to JPG', path: '/webp-to-jpg' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/webp-to-png': {
    path: '/webp-to-png',
    title: 'WebP to PNG Converter – Convert WebP Images to PNG',
    description: 'Convert WebP images to lossless PNG format with transparent background support.',
    canonical: `${BASE_URL}/webp-to-png`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Image Converters', path: '/webp-to-png' }, { label: 'WebP to PNG', path: '/webp-to-png' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/compress-image-to-20kb': {
    path: '/compress-image-to-20kb',
    title: 'Compress Image to 20KB Online – Free Tool',
    description: 'Compress photos and signature images strictly under 20KB for government application forms, UPSC, and banking portals.',
    canonical: `${BASE_URL}/compress-image-to-20kb`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Compress to 20KB', path: '/compress-image-to-20kb' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/compress-image-to-50kb': {
    path: '/compress-image-to-50kb',
    title: 'Compress Image to 50KB Online – Free Tool',
    description: 'Reduce image file size strictly under 50KB for passport photos, exam registration, and online portal uploads.',
    canonical: `${BASE_URL}/compress-image-to-50kb`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Compress to 50KB', path: '/compress-image-to-50kb' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/compress-image-to-100kb': {
    path: '/compress-image-to-100kb',
    title: 'Compress Image to 100KB Online – Free Tool',
    description: 'Resize and compress your photo under 100KB for NEET, JEE, SSC, and state exam application forms.',
    canonical: `${BASE_URL}/compress-image-to-100kb`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Compress to 100KB', path: '/compress-image-to-100kb' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/compress-image-to-200kb': {
    path: '/compress-image-to-200kb',
    title: 'Compress Image to 200KB Online – Free Tool',
    description: 'Compress certificates and larger photos strictly under 200KB for official document uploads.',
    canonical: `${BASE_URL}/compress-image-to-200kb`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Compress to 200KB', path: '/compress-image-to-200kb' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/compress-image-to-500kb': {
    path: '/compress-image-to-500kb',
    title: 'Compress Image to 500KB Online – Free Tool',
    description: 'Compress high-resolution photographs and scanned documents under 500KB instantly in browser.',
    canonical: `${BASE_URL}/compress-image-to-500kb`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Compress to 500KB', path: '/compress-image-to-500kb' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/image-to-pdf': {
    path: '/image-to-pdf',
    title: 'Image to PDF Converter – Convert Images to PDF',
    description: 'Convert JPG, PNG, and WebP images into a single professional PDF document securely in your browser.',
    canonical: `${BASE_URL}/image-to-pdf`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'PDF Tools', path: '/image-to-pdf' }, { label: 'Image to PDF', path: '/image-to-pdf' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/jpg-to-pdf': {
    path: '/jpg-to-pdf',
    title: 'JPG to PDF Converter – Convert JPG to PDF',
    description: 'Transform your JPG photos into high-quality PDF files instantly without uploading files to external servers.',
    canonical: `${BASE_URL}/jpg-to-pdf`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'PDF Tools', path: '/image-to-pdf' }, { label: 'JPG to PDF', path: '/jpg-to-pdf' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/png-to-pdf': {
    path: '/png-to-pdf',
    title: 'PNG to PDF Converter – Convert PNG to PDF',
    description: 'Convert PNG images to PDF documents quickly with high clarity and correct page orientation.',
    canonical: `${BASE_URL}/png-to-pdf`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'PDF Tools', path: '/image-to-pdf' }, { label: 'PNG to PDF', path: '/png-to-pdf' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/pdf-to-jpg': {
    path: '/pdf-to-jpg',
    title: 'PDF to JPG Converter – Convert PDF Pages to JPG',
    description: 'Extract pages from your PDF documents and convert them into high-resolution JPG images instantly.',
    canonical: `${BASE_URL}/pdf-to-jpg`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'PDF Tools', path: '/pdf-to-jpg' }, { label: 'PDF to JPG', path: '/pdf-to-jpg' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/pdf-to-png': {
    path: '/pdf-to-png',
    title: 'PDF to PNG Converter – Convert PDF Pages to PNG',
    description: 'Convert PDF document pages into crisp PNG image files directly in your web browser.',
    canonical: `${BASE_URL}/pdf-to-png`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'PDF Tools', path: '/pdf-to-jpg' }, { label: 'PDF to PNG', path: '/pdf-to-png' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/merge-pdf': {
    path: '/merge-pdf',
    title: 'Merge PDF Online – Combine PDF Files',
    description: 'Combine multiple PDF documents into a single organized PDF file securely and fast.',
    canonical: `${BASE_URL}/merge-pdf`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'PDF Tools', path: '/merge-pdf' }, { label: 'Merge PDF', path: '/merge-pdf' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/split-pdf': {
    path: '/split-pdf',
    title: 'Split PDF Online – Split PDF Pages',
    description: 'Extract specific pages or split large PDF files into multiple smaller documents easily.',
    canonical: `${BASE_URL}/split-pdf`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'PDF Tools', path: '/split-pdf' }, { label: 'Split PDF', path: '/split-pdf' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/rotate-pdf': {
    path: '/rotate-pdf',
    title: 'Rotate PDF Online – Rotate PDF Pages',
    description: 'Rotate PDF document pages clockwise or counter-clockwise by 90, 180, or 270 degrees.',
    canonical: `${BASE_URL}/rotate-pdf`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'PDF Tools', path: '/rotate-pdf' }, { label: 'Rotate PDF', path: '/rotate-pdf' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/compress-pdf': {
    path: '/compress-pdf',
    title: 'Compress PDF Online – Reduce PDF File Size',
    description: 'Reduce PDF file size efficiently for easier emailing, uploading, and sharing.',
    canonical: `${BASE_URL}/compress-pdf`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'PDF Tools', path: '/compress-pdf' }, { label: 'Compress PDF', path: '/compress-pdf' }],
    schemaType: 'WebApplication',
    includeInSitemap: true,
  },
  '/about': {
    path: '/about',
    title: 'About Us – Resize Files',
    description: 'Learn about Resize Files, our privacy-first client-side image and PDF processing technology.',
    canonical: `${BASE_URL}/about`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'About Us', path: '/about' }],
    schemaType: 'WebPage',
    includeInSitemap: true,
  },
  '/privacy': {
    path: '/privacy',
    title: 'Privacy Policy – Resize Files',
    description: 'Read our privacy policy regarding secure local browser-based image and PDF processing.',
    canonical: `${BASE_URL}/privacy`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Privacy Policy', path: '/privacy' }],
    schemaType: 'WebPage',
    includeInSitemap: true,
  },
  '/terms': {
    path: '/terms',
    title: 'Terms of Service – Resize Files',
    description: 'Read the terms of service for using Resize Files online image and PDF tools.',
    canonical: `${BASE_URL}/terms`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Terms of Service', path: '/terms' }],
    schemaType: 'WebPage',
    includeInSitemap: true,
  },
  '/contact': {
    path: '/contact',
    title: 'Contact Us – Resize Files',
    description: 'Get in touch with the Resize Files team for support, feedback, or inquiries.',
    canonical: `${BASE_URL}/contact`,
    breadcrumbs: [{ label: 'Home', path: '/' }, { label: 'Contact Us', path: '/contact' }],
    schemaType: 'WebPage',
    includeInSitemap: true,
  },
};
